package com.enrique.khttpconstants

class HttpHeaders {
    companion object {
        const val ACCEPT = "Accept"
        const val ACCEPT_CHARSET = "Accept-Charset"
        const val ACCEPT_ENCODING = "Accept-Encoding"
        const val ACCEPT_LANGUAGE = "Accept-Language"
        const val AUTHORIZATION = "Authorization"
        const val CACHE_CONTROL = "Cache-Control"
        const val CONNECTION = "Connection"
        const val CONTENT_LENGTH = "Content-Length"
        const val CONTENT_TYPE = "Content-Type"
        const val COOKIE = "Cookie"
        const val DATE = "Date"
        const val ETAG = "ETag"
        const val EXPECT = "Expect"
        const val EXPIRES = "Expires"
        const val HOST = "Host"
        const val IF_MATCH = "If-Match"
        const val IF_MODIFIED_SINCE = "If-Modified-Since"
        const val IF_NONE_MATCH = "If-None-Match"
        const val IF_UNMODIFIED_SINCE = "If-Unmodified-Since"
        const val LAST_MODIFIED = "Last-Modified"
        const val LOCATION = "Location"
        const val ORIGIN = "Origin"
        const val PRAGMA = "Pragma"
        const val REFERER = "Referer"
        const val SERVER = "Server"
        const val SET_COOKIE = "Set-Cookie"
        const val TRANSFER_ENCODING = "Transfer-Encoding"
        const val UPGRADE = "Upgrade"
        const val USER_AGENT = "User-Agent"
        const val VARY = "Vary"
        const val VIA = "Via"
        const val WARNING = "Warning"
        const val WWW_AUTHENTICATE = "WWW-Authenticate"
    }
}
